development:
  adapter: postgresql  
  database: d93qqiu8kd0d0k
  pool: 5
  timeout: 5000
  host: ec2-23-23-215-150.compute-1.amazonaws.com
  username: clsszvwngsmmpa
  password: uXAvZQ73xnit76HkElqRg5suAI
